name: React CD

on:
  push:
    branches: ['prod']
  pull_request:
    branches: ['prod']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Check Format
        run: yarn run format

      - name: Build
        run: yarn run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: build
    env:
      AZURE_WEBAPP_NAME: shooting-star-reactjs-training
      AZURE_WEBAPP_PACKAGE_PATH: .
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .

      - name: Display structure
        run: ls -R

      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
